import { json } from "@remix-run/node";

export const loader = async () => {
    return json([
        {   
            id: 1,
            size: 2,
            order: 1,
            title: "Project 01",
            description: "Size 1",
            image: "https://picsum.photos/1440/400?random=1",
        },
        {   
            id: 2,
            size: 4,
            order: 2,
            title: "Project 02",
            description: "Size 3",
            image: "https://picsum.photos/1440/400?random=2",
        },
        {   
            id: 3,
            size: 6,
            order: 3,
            title: "Project 03",
            description: "Size 4",
            image: "https://picsum.photos/1440/400?random=3",
        },
        {   
            id: 4,
            size: 2,
            order: 4,
            title: "Project 04",
            description: "Size 1",
            image: "https://picsum.photos/1440/400?random=4",
        },
        {   
            id: 5,
            size: 2,
            order: 5,
            title: "Project 05",
            description: "Size 3",
            image: "https://picsum.photos/1440/400?random=5",
        },
        {   
            id: 6,
            size: 2,
            order: 6,
            title: "Project 06",
            description: "Size 4",
            image: "https://picsum.photos/1440/400?random=6",
        },
       
        {   
            id: 7,
            size: 3,
            order: 7,
            title: "Project 07",
            description: "Size 4",
            image: "https://picsum.photos/1440/400?random=7",
        },
        {   
            id: 8,
            size: 3,
            order: 8,
            title: "Project 08",
            description: "Size 2",
            image: "https://picsum.photos/1440/400?random=8",
        },
        {   
            id: 9,
            size: 4,
            order: 9,
            title: "Project 09",
            description: "Size 2",
            image: "https://picsum.photos/1440/400?random=9",
        },
        {   
            id: 10,
            size: 2,
            order: 10,
            title: "Project 10",
            description: "Size 2",
            image: "https://picsum.photos/1440/400?random=10",
        },
        {   
            id: 11,
            size: 3,
            order: 11,
            title: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries",
            description: "Size 2",
            image: "https://picsum.photos/1440/400?random=11",
        },
    ]);
}